# Generated by Django 5.2 on 2025-08-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusermodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='int_id',
            field=models.IntegerField(blank=True, default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
